# SPDX-FileCopyrightText: 2024 diggsweden/eudiw-wallet-token-lib
#
# SPDX-License-Identifier: CC0-1.0

---
policies:
  - type: commit
    spec:
      dco: true
      gpg:
        required: true
      header:
        length: 100
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      conventional:
        types: ["chore", "build","docs","ci","perf", "refactor", "style", "test", "release"]
        scopes: [".*"]
        descriptionLength: 92
