# SPDX-FileCopyrightText: 2024 Digg
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
  ".github/pull_request_template.md",
  "renovate.json",
  "src/test/resources/simplelogger.properties",
  "CHANGELOG.md",
 "docs/DEVELOPMENT.md",
  "jreleaser.yml",
  "**/*/pmd_default_java.xml",
  "README.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "diggsweden. <https://github.com/diggsweden>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]

path = [
    "**/*/eclipse-java-google-style.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "google/styleguide"
SPDX-License-Identifier = "CC-BY-3.0"


[[annotations]]
path = [
    "**/*/google_checks.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "checkstyle/checkstyle"
SPDX-License-Identifier = "CC0-1.0"