# SPDX-FileCopyrightText: 2025 diggsweden/eudiw-wallet-token-lib
#
# SPDX-License-Identifier: CC0-1.0

---
name: OpenSSF Scorecard analysis

on:
  push:
    branches:
      - main
  schedule:
    # Weekly on Saturdays at 01:30 UTC
    - cron: "30 1 * * 6"

permissions:
  contents: read  # Best Security practice. Jobs only get read as base, and then permissions are added as needed

jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: diggsweden/reusable-ci/.github/workflows/security-openssf-scorecard.yml@v1