# SPDX-FileCopyrightText: 2025 diggsweden/eudiw-wallet-token-lib
#
# SPDX-License-Identifier: CC0-1.0

---
name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2am UTC
  workflow_dispatch:

permissions: read-all

jobs:
  scorecard:
    uses: diggsweden/reusable-ci/.github/workflows/security-openssf-scorecard.yml@v2
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read