# SPDX-FileCopyrightText: 2024 diggsweden/eudiw-wallet-token-lib
#
# SPDX-License-Identifier: CC0-1.0
---
name: Release Lib

on: [workflow_call]  # yamllint disable-line rule:truthy

permissions:
  contents: read

env:
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress --errors --fail-at-end -Dstyle.color=always -DinstallAtEnd=true -DdeployAtEnd=true"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write 
      issues: write
    
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          fetch-depth: 0
          
      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Fetch git-cliff templates
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: diggsweden/.github
          path: .github-templates
          ref: main

          
      - name: Generate Releasenotes
        uses: orhun/git-cliff-action@4a4a951bc43fafe41cd2348d181853f52356bee7 # v4.4.2
        with:
          config: .github-templates/gitcliff-templates/default.toml
          args: --latest
        env:
          OUTPUT: ReleasenotesTmp
          GITHUB_REPO: ${{ github.repository }}
       
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        with:
          gpg_private_key: ${{ secrets.OSPO_BOT_GPG_PRIV }} 
          passphrase: ${{ secrets.OSPO_BOT_GPG_PASS }}      
      
      - name: Release to Maven Central and GitHub Releases
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.OSPO_BOT_GPG_PUB }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.OSPO_BOT_GPG_PRIV }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.OSPO_BOT_GPG_PASS }}
          GITHUB_ACTOR: ${{ github.actor }} 
          PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          # shellcheck disable=SC2086 
          mvn $MAVEN_CLI_OPTS deploy --settings .mvn/settings.xml -Pcentral-release

          # shellcheck disable=SC2086 
          mvn $MAVEN_CLI_OPTS jreleaser:full-release -DskipTests

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: jreleaser-logs
          path: |
            target/jreleaser/trace.log
            target/jreleaser/output.properties